server:
  port: 8081
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=true&amp;characterEncoding=UTF-8
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
mybatis:
  type-aliases-package: com.xh.model.user.pojo.*,com.xh.model.admin.pojo.*
logging:
  level:
    com.xh.model.user.dao : debug
    com.xh.model.admin.dao : debug